### ISSUE TITLE
Can't get it to work with MySQL database

### ISSUE THREAD

**Issue by fluxxus** [PHPBootstrapTableEdit/PHPBootstrapTableEdit#1]
Hi! 

As the title says, I am having difficulties making it work. `MySQL` database with one simple table(working nicely with your other datagrid script nicely for many years BTW). 

The above didn't work, so I tried with replicating the demo `MySQL` instead of `SQLite`. Followed your instructions in the `example.sql` file, copy-pasted the required code - still no luck.

This is the error I got with both my data and yours:
`Fatal error: Uncaught PDOException: SQLSTATE[42000]: Syntax error or access violation: 1248 Every derived table must have its own alias`.

P.S.
I googled the error, tried a few suggestions but it didn't help. Keep in mind my PHP skills are lacking, I use it sparingly and when I do it is nothing complicated/advanced.

Thx

**Comment by PHPBootstrapTableEdit** [comment]
Thank for submitting this issue, this should be fixed now. I also found some issues with pgsql and binary uploads that I fixed.

**Comment by fluxxus** [comment]
Yeah, looks good now! Thx
